config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'session#welcome'

  get '/home' => 'users#home'
  get '/transactions' => 'users#transactions'

  resources :transactions, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owned_stock.rb
class OwnedStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock

  def buy(amount)
    self.amount += amount
    if self.save
      return true
    else
      return false
    end
  end

end

app/models/stock.rb
require 'httparty'

class Stock < ApplicationRecord
  has_many :transactions
  has_many :users, through: :transactions
  has_many :owned_stocks, through: :users

  @stock_cache = {}

  def self.stock_cache
    @stock_cache
  end

  def stock_cache
    self.class.stock_cache
  end

  def self.supported?(ticker_symbol)
    url = "https://api.iextrading.com/1.0/stock/#{ticker_symbol}/quote"
    uri = URI(url)
    response = Net::HTTP.get(uri)
    if response == "Unknown symbol"
      return false
    else
      return true
    end
  end

  def self.current_value(ticker_symbol)
    url = "https://api.iextrading.com/1.0/stock/#{ticker_symbol}/quote"
    uri = URI(url)
    response = Net::HTTP.get(uri)
    data = JSON.parse(response)
    return data
  end

  def self.update_all_for_user(user_id)
    User.find(user_id).owned_stocks.each do |s|
      if !Stock.stock_cache.has_key?(s.stock.ticker_symbol.to_sym)
        puts s.stock.ticker_symbol + " Not in cache"
        s.stock.update_value
      end
    end
  end

  def update_value
    data = Stock.current_value(self.ticker_symbol)
    self.todays_open = data["open"]
    self.current_value = data["latestPrice"]
    if self.save
      insertStock(self.ticker_symbol, data["open"], data["latestPrice"])
      return true
    else
      return false
    end
  end

  def current_color
    if self.current_value > self.todays_open
      return "text-success"
    elsif self.current_value == self.todays_open
      return "text-secondary"
    elsif self.current_value < self.todays_open
      return "text-danger"
    else
      return "text-dark"
    end
  end
end

private

def insertStock(ticker_symbol, current_value, todays_open)
    Thread.new {
      Stock.stock_cache[ticker_symbol.to_sym] = {
                                                  :current_value => current_value,
                                                  :todays_open => todays_open
                                                }
      puts "Updating cache with " + ticker_symbol
      sleep(60);
      Stock.stock_cache.delete(ticker_symbol.to_sym);
      puts "now reset"
    }
  end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :stock

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  validates :email, uniqueness: true

  has_many :transactions
  has_many :stocks, through: :transactions
  has_many :owned_stocks

  after_initialize :set_defaults, unless: :persisted?

  def set_defaults
    self.cash = 5000
  end

  def buy(symbol, amount)
    if !Stock.supported?(symbol)
      puts "We don't support this stock"
      return false
    else
      stock = Stock.find_or_create_by(ticker_symbol: symbol)
      stock.update_value
    end

    if (stock.current_value * amount) <= self.cash
      self.transactions.create(stock: stock, value_of_each: stock.current_value, number_of_shares: amount, bought: true)
      owned_stock = OwnedStock.find_by({user: self, stock_id: stock})
      if owned_stock
        owned_stock.buy(amount)
      else
        owned_stock = OwnedStock.create({user: self, stock: stock, amount: amount})
      end
      self.cash = self.cash - (stock.current_value * amount)
      self.save
      puts "Bought some stock"
    else
      puts "You don't have enough money for this amount"
      return false
    end
    return true
  end

  def portfolio_value
    amount = 0
    self.owned_stocks.each do |s|
      amount += s.stock.current_value * s.amount
    end
    return ActionController::Base.helpers.number_to_currency(amount)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def validate_user
    if current_user.nil?
      redirect_to root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def welcome
    if signed_in?
      redirect_to home_path
    else
      render :welcome
    end
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create
    current_user.buy(transaction_params[:stock_id], transaction_params[:number_of_shares].to_i )
    redirect_to home_path
  end
end

private

  def transaction_params
    params.require(:transactions).permit(:stock_id, :number_of_shares)
  end

app/controllers/users_controller.rb
require 'pry'

class UsersController < ApplicationController

  before_action :validate_user

  def home
    @user = current_user
    Stock.update_all_for_user(current_user.id)
    @cash = ActionController::Base.helpers.number_to_currency(current_user.cash)
    @value = current_user.portfolio_value
    @transaction = current_user.transactions.new
    render :home
  end

  def transactions
    @transactions = current_user.transactions.reverse
    render :transactions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="http://www.techtalentpipeline.nyc/">TTP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if signed_in? %>
      <li class="nav-item">
        <%= link_to "Home", home_path, html_options = {:class => "nav-link"} %>
      </li>
      <li class="nav-item">
        <%= link_to "Transactions", transactions_path, html_options = {:class => "nav-link"} %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, html_options = {:class => "nav-link"} %>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Home", root_path, html_options = {:class => "nav-link"} %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, html_options = {:class => "nav-link"} %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<%= content_tag(:div, flash[:error], :id => "flash_error", style: "color: #e60000; font-weight: bolder;") if flash[:error] %>
<%= content_tag(:div, flash[:notice], :id => "flash_notice", style: "color: #00cc00; font-weight: bolder;") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert", style: "color: #e6e600; font-weight: bolder;") if flash[:alert] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TtpStockApp</title>
    <%= csrf_meta_tags %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/session/welcome.html.erb
<div class="container">
  <h1>
    Welcome to TTP Stocks
  </h1>

  <p>This is an application where you can buy stock. This was made for the Tech Talent Pipeline assessment project. You can sign in through the email link if you want to try out this super cool application.</p>


</div>

app/views/users/home.html.erb
<br>
<div class="container">
  <div class="row text-center">
    <div class="col-12">
      <h2>Portfolio (<%= @value %>)</h2>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-sm-6 d-flex justify-content-center">
      <div class="owned_stock_list">
        <% @user.owned_stocks.each do |s| %>
          <div>
            <b class="text-primary"><%= s.stock.ticker_symbol %></b> - <%= s.amount.to_i %> shares - <%= ActionController::Base.helpers.number_to_currency(s.amount * s.stock.current_value)  %>
            <br>
            Current Value: <b class="<%= s.stock.current_color %>"><%= ActionController::Base.helpers.number_to_currency(s.stock.current_value) %></b>
          </div>
          <hr>
        <% end %>
      </div>
    </div>

    <hr>
    <br></br>
    <br></br>
    <br></br>
    <div class="col-sm-6 text-center">
      <h3>Cash - <%= @cash %></h3>

      <%= form_for :transactions, url: "/transactions" do |f| %>
        <br>
        <%= f.text_field :stock_id, placeholder: "Ticker" %>
        <br>
        <%= f.text_field :number_of_shares, placeholder: "Quantity" %>
        <br>
        <%= f.submit "Buy" %>
      <% end %>

      <div id="form_alert"></div>
    </div>

  </div>

</div>

app/views/users/transactions.html.erb
<div class="container text-center">
  <h1>Transactions</h1>

  <div class="transaction_list">
    <small>Most recent first</small>
    <% @transactions.each do |d| %>
      <div class="transactions">
        <%= d.stock.ticker_symbol %> - <%= d.number_of_shares %> Shares - Each: <%= d.value_of_each %>
      </div>
      <hr>
    <% end %>

  </div>

</div>